platform :ios, '13.0'
use_frameworks!

target 'objc-sdk-test-app' do
  pod 'objc-sdk', :path => '../'
  pod '!ProtoCompiler-gRPCPlugin', '~> 1.0'
end

target 'objc-sdk_Tests' do
  pod 'objc-sdk', :path => '../'
end
