platform :ios, '13.0'
use_frameworks!

target 'SensoryCloudExampleApp' do
  pod 'SensoryCloud', :path => '../'
  pod '!ProtoCompiler-gRPCPlugin', '~> 1.0'
end

target 'SensoryCloudTests' do
  pod 'SensoryCloud', :path => '../'
end
